# render.yaml — Modular Chatbot (Backend)
services:
  - type: web
    name: modular-chatbot-backend
    env: node
    region: oregon
    plan: free
    # Usamos o root do repositório para que o pnpm enxergue o pnpm-workspace.yaml
    rootDir: .
    runtime: node
    # Se você tem .nvmrc com "20", o Render já respeita.
    buildCommand: >
      corepack enable &&
      corepack prepare pnpm@9.9.0 --activate &&
      pnpm i -w --frozen-lockfile --prod=false &&
      pnpm -C packages/shared build &&
      pnpm -C packages/backend build
    startCommand: node packages/backend/dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      # Evita rodar husky no build
      - key: HUSKY
        value: "0"
      # Liberar CORS só para o domínio do frontend (ajuste após deploy da Vercel)
      - key: CORS_ORIGIN
        value: https://SEU-APP.vercel.app
    healthCheckPath: /health
