apiVersion: apps/v1
kind: Deployment
metadata:
  name: modular-chatbot-frontend
  namespace: modular-chatbot
  labels:
    app: modular-chatbot-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: modular-chatbot-frontend
  template:
    metadata:
      labels:
        app: modular-chatbot-frontend
    spec:
      containers:
        - name: frontend
          image: modular-chatbot-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: modular-chatbot-config
                  key: NODE_ENV
            - name: VITE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: modular-chatbot-config
                  key: VITE_API_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: modular-chatbot-frontend
  namespace: modular-chatbot
  labels:
    app: modular-chatbot-frontend
spec:
  selector:
    app: modular-chatbot-frontend
  ports:
    - port: 80
      targetPort: 5173
      protocol: TCP
  type: ClusterIP
