apiVersion: v1
kind: Secret
metadata:
  name: modular-chatbot-secrets
  namespace: modular-chatbot
type: Opaque
data:
  # Para gerar os valores base64, use os comandos abaixo:
  # echo -n "sua-openai-api-key-aqui" | base64
  # echo -n "sua-redis-password-aqui" | base64

  # Exemplo com valores reais (substitua pelos seus):
  OPENAI_API_KEY: "c2stcHJvai1fd3o1emM0T1VfTDhrNnR6WklBZXlsd2owalRwSHRxdEVWUVFJakdtMFVoSzFoUlgwTnlvQXB5amlfTVgwR2JkUnhyVmNIaTRfVDNCbGJrRko3bEFreW0zenF6VEdKaWpWeUg5bDhmdXhpb3VodEFtcjNOZmZtLUZaeDBHVlhVLWxHbHBZNHN5QXY3TGdjUU9uTWowalQ3Um40QQ==" # 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
  REDIS_PASSWORD: "" # senha-redis-here
