name: CI

on:
  pull_request:
  push:
    branches: [main, master]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      HUSKY: "0"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm (follows packageManager)
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install deps (workspace)
        run: pnpm install -w --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build shared
        run: pnpm -C packages/shared build

      - name: Build backend
        run: pnpm -C packages/backend build

      - name: Build frontend
        run: pnpm -C packages/frontend build
