name: CI

on:
  pull_request:
  push:
    branches: [main, master]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      HUSKY: "0" # não rodar hooks em CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Instala pnpm (evita "Unable to locate executable file: pnpm")
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      # Node 20 + cache de pnpm (lockfile na raiz do monorepo)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install deps (workspace)
        run: pnpm install -w --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build shared
        run: pnpm -C packages/shared build

      - name: Build backend
        run: pnpm -C packages/backend build

      - name: Build frontend
        run: pnpm -C packages/frontend build
