jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Enable Corepack
        run: corepack enable

      - name: Install deps
        run: pnpm install -w --no-frozen-lockfile

      - name: Build backend
        run: pnpm -C packages/backend build

      - name: Build frontend
        run: pnpm -C packages/frontend build
