# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [master, main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Instala o pnpm no PATH do runner
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      # Node + cache de dependências do pnpm
      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install deps (workspace)
        run: pnpm install -w --no-frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build backend
        run: pnpm -C packages/backend build

      - name: Build frontend
        run: pnpm -C packages/frontend build
