name: Deploy Frontend (Vercel)

on:
  push:
    branches: [main, master]
  workflow_dispatch:

concurrency:
  group: deploy-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel deploy
        run: |
          curl -fsSL -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
